export const suggestions = [
  "Latest Bollywood songs",
  "Top Hindi songs June 2025",
  "Trending Indian music videos",
  "Bewajah – Himesh Reshammiya",
  "Raanjhan – Do Patti",
  "Zamaana Lage – Metro… In Dino",
  "Aashiq Tera – Reels trending",
  "Silsila – Dhoom Dhaam",
  "Tu Hai Toh Main Hoon – Sky Force",
  "Azaad Hai Tu – Azaad",
  "Ajeeb O Gareeb – Azaad",
  "Fateh Kar Fateh – Fateh",
  "Jaane Tu – Chhaava",
  "Hum Aapke Bina – Sikandar",
  "Khudaya Ishq – Abir Gulaal",
  "Doriyaan – Abir Gulaal",
  "Sar Aankhon Pe Mere – Sitaare Zameen Par",
  "Ruaa Ruaa – Fateh",
  "Rehna Kol – Loveyappa",
  "So Lene De – Ground Zero",
  "Jaadu – Jewel Thief",
  "Sapphire – Ed Sheeran ft. Arijit Singh",
  "Qatal – Guru Randhawa",
  "GF BF – Gurinder Seagal",
  "Chuttamalle – Telugu hit",
  "Besos – Shikhar Dhawan & Jacqueline",
  "Tauba Tauba – Karan Aujla",
  "Not Ramaiya Vastavaiya – Jawan",
  "Kaavaalaa – Tamil viral",
  "Yentamma – Kisi Ka Bhai Kisi Ki Jaan",
  "Gulabi Sadi – Marathi viral",
  "Chahte Hain – Shilpa Rao & Raghav Chaitanya",
  "Abhi Kabhi Sabhi – Rameez Khalid",
  "Mi Amore – INGA & Shor Police",
  "Buddy – Priya Mali",
  "Hota Hai Aisa Kahaan – Anurag Mishra",
  "Tere Vaaste – Zara Hatke Zara Bachke",
  "O Saki Saki – Neha Kakkar version",
  "Dekhha Tenu – Mr & Mrs Mahi",
  "Hayyoda x Chaleya – Anirudh Ravichander",
  "DIL E NADAAN – Sajid–Wajid",
  "Jaana Samjho Na – Bhool Bhulaiyaa 3",
  "Soni Soni – Ishq Vishk Rebound",
  "Jaanam – Bad Newz",
  "Sadqay – Janam Pyaar Tumse Hai",
  "Akhiyaan Gulaab – Teri Baaton Mein Aisa Uljha Jiya",
  "Jaanam – Bad Newz (duplicate but high search)",
  "Sadqay – romantic mashup",
  "Chale Aana – De De Pyaar De",
  "Tere Pyaar Mein – Tu Jhoothi Main Makkaar",
  "Bhool Bhulaiyaa 3 – various hits",
  "Bollywood romantic mashup 2025",
  "Bollywood EDM mashup 2025",
  "Bollywood 90s retro classics",
  "Punjabi romantic songs",
  "Punjabi party songs",
  "Lo-fi Bollywood beats",
  "Indie alt‑pop Indian songs",
];

// {
//   "id": "WrjTwTyT1jA",
//   "title": "Kumar Sanu Hit Songs | 90s Superhit Hindi Romantic Songs | Sadabahar Song | Bollywood Songs Jukebox",
//   "description": "Presenting a soul-soothing jukebox of 90s superhit Hindi romantic songs that defined a generation. From heart-melting love ...",
//   "channelId": "UCJrDMFOdv1I2k8n9oK_V21w",
//   "channelTitle": "Tips Official",
//   "publishedAt": "2025-06-05T13:30:33Z",
//   "thumbnail": "https://i.ytimg.com/vi/WrjTwTyT1jA/hqdefault.jpg",
//   "duration": "PT2H40M13S"
// }
